# Generated by Django 4.2 on 2023-05-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=80)),
                ('first_name', models.CharField(max_length=50)),
            ],
        ),
    ]
