# Generated by Django 4.2 on 2023-05-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_male',
            field=models.BooleanField(null=True),
        ),
    ]
