# Generated by Django 4.2 on 2023-05-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_male',
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
